osx_image: xcode10.2

dist: bionic

language: node_js
node_js: 10

matrix:
  include:
    - os: osx
    - os: linux

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - rpm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo snap install snapcraft --classic; fi

script:
  - yarn build
  - yarn package --publish always

branches:
  only:
    - master
    # - /^hotfix\/.*$/
    # - /^release\/.*$/
  
  # except:
  #   - "/^v\\d+\\.\\d+\\.\\d+$/"