
name: CI

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on: [push, pull_request]

env:
  CI: true

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      # - name: Run Test
      #   run: |
      #     npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build web
        run: |
          npx ionic build --prod

  build:
    name: build
    if: contains(github.ref, 'refs/tags/v')
    needs: test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run package --publish always
